### ISSUE TITLE
Do not hijack CTRL+F

### ISSUE THREAD

**Issue by Zambito1** [schemeorg-community/index.scheme.org#37]
Please do not hijack CTRL+F to select the search box. Using the browsers search function is useful for highlighting keywords on a page. This isn't possible to do with the current behavior.

**Comment by Zambito1** [comment]
The issue is caused here: https://github.com/schemeorg-community/index.scheme.org/blob/32e1afcfe423a158ac8ce014f5c0b8399d12a1ea/static/js/scmindex.js#L95

**Comment by arvyy** [comment]
I'm considering copying google and using `/` key to focus the query field. Would that be better?

**Comment by Zambito1** [comment]
Some browsers (such as qutebrowser) actually use `/` instead to search the page. I'm not sure how it behaves on Google, but on GitHub I think using `/` will inconsistently jump to the search box in qutebrowser.

I think the best would be to just not have a keybinding to jump to the search. Users can use the tab key to cycle through elements if they want, or they could use keyboard navigation plugins / browsers.

**Comment by Zambito1** [comment]
I think CTRL+`/` may work. I know that would not interfere with what I want to do.

**Comment by arvyy** [comment]
I've changed to ctrl + / for the time being (I definitely want this as a feature, and not rely on tab or plugins). Will probably make it user-configurable in the future.

**Comment by Zambito1** [comment]
Thanks!
